version: 2.1
executors:
  my-executor:
    docker:
      - image: devkitpro/devkitarm
jobs:
  build:
    executor: my-executor
    steps:
    - run: apt-get update && apt-get install -y openssh-client git
    - checkout
    - run:
          name: Build
          command: |
            ./build_samples.sh
workflows:
  build:
    jobs:
    - build
